const {DataTypes} = require ('sequelize');
const { sequelize } = require('../config/bdCon');



const   Afb_data = sequelize.define('Afb_data',{
    DNI:{type:DataTypes.STRING(8),allowNull:false, primaryKey:true},
    X_APPATERNO: { type: DataTypes.STRING(80) },
    X_APMATERNO: { type: DataTypes.STRING(80) },
    X_NOMBRE: { type: DataTypes.STRING(120) },
    SUCURSAL: { type: DataTypes.STRING(8) },
    TIENDA: { type: DataTypes.STRING(120) },
    NOM_ASESOR: { type: DataTypes.STRING(50) },
    COD_ASESOR: { type: DataTypes.STRING(10) },
    INGRESO: { type: DataTypes.STRING(10) },
    CAPACIDAD: { type: DataTypes.STRING(10) },
    OFERTA_MAX: { type: DataTypes.STRING(10) },
    MORADO: { type: DataTypes.STRING(10) },
    IdCampania: { type: DataTypes.STRING(10) },
    Landing_PP: { type: DataTypes.STRING(10) },
    Landing_CC: { type: DataTypes.STRING(10) },
    Landing_Moto: { type: DataTypes.STRING(100) },
    Tipo_oferta: { type: DataTypes.STRING(50) },
    Tipo_verificacion: { type: DataTypes.STRING(50) },
    TELF_1: { type: DataTypes.STRING(9) },
    TELF_2: { type: DataTypes.STRING(9) },
    TELF_3: { type: DataTypes.STRING(9) },
    TELF_4: { type: DataTypes.STRING(9) },
    TELF_5: { type: DataTypes.STRING(9) },
    GRUPO_RIESGO: { type: DataTypes.STRING(100) },
    Canal: { type: DataTypes.STRING(60) },
    Tipovisita: { type: DataTypes.STRING(60) },
    Tasa_1: { type: DataTypes.STRING(20) },
    Tasa_2: { type: DataTypes.STRING(20) },
    Tasa_3: { type: DataTypes.STRING(20) },
    Tasa_4: { type: DataTypes.STRING(20) },
    Tasa_5: { type: DataTypes.STRING(20) },
    Tasa_6: { type: DataTypes.STRING(20) },
    Tasa_7: { type: DataTypes.STRING(20) },
    segmento: { type: DataTypes.STRING(60) },
    PLAZO: { type: DataTypes.STRING(10) },
    Campaña: { type: DataTypes.STRING(60) },
    TEM: { type: DataTypes.STRING(60) },
    Desgravamen: { type: DataTypes.STRING(10) },
    CUOTA: { type: DataTypes.STRING(10) },
    Edad: { type: DataTypes.STRING(10) },
    Oferta_12M: { type: DataTypes.STRING(20) },
    Tasa_12M: { type: DataTypes.STRING(20) },
    Desgravamen_12M: { type: DataTypes.STRING(20) },
    CUOTA_12M: { type: DataTypes.STRING(20) },
    Oferta_18M: { type: DataTypes.STRING(20) },
    Tasa_18M: { type: DataTypes.STRING(20) },
    Desgravamen_18M: { type: DataTypes.STRING(20) },
    CUOTA_18M: { type: DataTypes.STRING(20) },
    Oferta_24M: { type: DataTypes.STRING(20) },
    Tasa_24M: { type: DataTypes.STRING(20) },
    Desgravamen_24M: { type: DataTypes.STRING(20) },
    CUOTA_24M: { type: DataTypes.STRING(20) },
    Oferta_36M: { type: DataTypes.STRING(20) },
    Tasa_36M: { type: DataTypes.STRING(20) },
    Desgravamen_36M: { type: DataTypes.STRING(20) },
    CUOTA_36M: { type: DataTypes.STRING(20) },
    Validador_Telefono: { type: DataTypes.STRING(10) },
    Prioridad: { type: DataTypes.STRING(10) },
    Nombre_prioridad: { type: DataTypes.STRING(255) },
    Deuda_1: { type: DataTypes.STRING(10) },
    Entidad_1: { type: DataTypes.STRING(60) },
    Deuda_2: { type: DataTypes.STRING(10) },
    Entidad_2: { type: DataTypes.STRING(60) },
    Deuda_3: { type: DataTypes.STRING(10) },
    Entidad_3: { type: DataTypes.STRING(60) },
    DEPARTAMENTO: { type: DataTypes.STRING(80) },
    PROVINCIA: { type: DataTypes.STRING(80) },
    DISTRITO: { type: DataTypes.STRING(80) },
    sucursal_comercial: { type: DataTypes.STRING(80) },
    Agencia_comercial: { type: DataTypes.STRING(80) },
    Region_comercial: { type: DataTypes.STRING(80) },
    Ubicacion: { type: DataTypes.STRING(80) },
    Flag_telefono: { type: DataTypes.STRING(10) },
    OfertaMaximaSinSeguro: { type: DataTypes.STRING(10) },
    Color_gestion: { type: DataTypes.STRING(50) },
    OFERTA_FINAL: { type: DataTypes.STRING(10) },
    GARANTIA: { type: DataTypes.STRING(60) },
    Oferta_Minima_Paperless: { type: DataTypes.STRING(60) },
    CET: { type: DataTypes.STRING(50) },
    CEL1: { type: DataTypes.STRING(10) },
    CEL2: { type: DataTypes.STRING(10) },
    CEL3: { type: DataTypes.STRING(10) },
    CEL4: { type: DataTypes.STRING(10) },
    CEL5: { type: DataTypes.STRING(10) },
    RANGO_EDAD: { type: DataTypes.STRING(10) },
    RANGO_OFERTA: { type: DataTypes.STRING(20) },
    RANGO_SUELDO: { type: DataTypes.STRING(30) },
    PEER: { type: DataTypes.STRING(30) },
    PROP_COMER: { type: DataTypes.STRING(30) }
  }, {
    tableName: 'Afb_Data',
    timestamps: false,
  });
  

  
module.exports = {Afb_data};
